# Site settings
title: Amanda Dukawa - Full Stack Journey
description: Welcome to my blog where I share my journey as a Full Stack Developer, insights, and projects in web development and design.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "http://madukisp.github.io" # the base hostname & protocol for your site

# User settings
username: Amanda Dukawa
user_description: I'm Amanda, a student and an aspiring Full Stack Developer with a background in design and video editing. I am passionate about building responsive and interactive web solutions.
user_title: Dev Full-Stack
email: madukisp@gmail.com
linkedin_username: https://www.linkedin.com/in/amanda-duque-kawa
github_username:  madukisp
medium_username: https://medium.com/@madukisp

# Google Analytics
google-analytics:
  id: "G-8YN2RLG9DD"


exclude: ['package.json', 'src' , 'node_modules']
